npmRegistryServer: "https://registry.yarnpkg.com"
nodeLinker: "node-modules"
yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  # Resolves yarn 2 peer dependency conflict due to @types/node requirement set here:
  # https://github.com/Codex-/cosmiconfig-typescript-loader/blob/d5ce8bb4ee75fec7efd6e73612d9fe076a844810/package.json#L34
  'cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      '@types/node':
        optional: true
