name: PR Checks
on: [push, pull_request]
jobs:

  # Checks that PR commits match the Conventional Commmit format
  # See: https://www.conventionalcommits.org/en/v1.0.0/
  commitlint:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4  # See: https://github.com/wagoid/commitlint-github-action
        with:
          configFile: .commitlintrc.yml

  install-node-modules:
    name: Install node_modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: Validate cache
        run: yarn install --frozen-lockfile

  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint

  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: format-check
        run: yarn format:check

  typescript:
    name: Check TypeScript
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: typescript-check
        run: yarn tsc
